### ISSUE TITLE
header for more languages

### ISSUE THREAD

**Issue by larryxiao** [shanzi/autoHEADER#2]
support header for more languages: C, C++, JAVA ...
can refer to http://www.tiobe.com/index.php/content/paperinfo/tpci/index.html

**Comment by shanzi** [comment]
Adding header for more language needs some refactor on the codes.
I am still thinking about it.

**Comment by larryxiao** [comment]
thanks for quick response!

sorry that I didn't see you've already included many popular languages ..
I see new languages can be easily included with easy modification 

I think it's good for now ..
