### ISSUE TITLE
Enclosing box

### ISSUE THREAD

**Issue by segeljakt** [shanzi/autoHEADER#3]
Could you make the box enclose?

    /******************************************************************************
    *     File Name           :     file.h                                        *
    *     Created By          :     John Appleseed                                *
    *     Creation Date       :     [2016-11-03 20:48]                            *
    *     Last Modified       :     [AUTO_UPDATE_BEFORE_SAVE]                     *
    *     Description         :     File of files.                                *
    ******************************************************************************/

why? because it looks pretty :D 🐰

**Comment by shanzi** [comment]
@klassegeljakt sorry this repository is no longer actively maintaining. Perhaps a better choice might be some code snippets plugin such as [ultisnips](https://github.com/SirVer/ultisnips)
